name: example
description: example of functional data

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  functional_data:

dev_dependencies:
  build_runner: ^1.12.1
  build_resolvers: ">=2.0.0"
  functional_data_generator: