name: functional_data_generator
version: 0.2.4
description: >-
  Simple and non-intrusive code generator for boilerplate of data types.
authors:
  - Sander Kersten <spkersten@gmail.com>
homepage: https://github.com/spkersten/dart_functional_data

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  analyzer: ">=0.34.0 <0.39.0"
  build: ^1.1.0
  source_gen: ^0.9.2
  collection: ^1.14.12
  functional_data: ">=0.2.0 <0.3.0"

dev_dependencies:
  build_runner:
