name: functional_data_generator
version: 0.3.3
description: >-
  Simple and non-intrusive code generator for boilerplate of data types.
authors:
  - Sander Kersten <spkersten@gmail.com>
homepage: https://github.com/spkersten/dart_functional_data

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ">=0.38.1 <0.40.0"
  build: ^1.3.0
  source_gen: ^0.9.6
  collection: ^1.14.12
  functional_data: ">=0.2.0 <0.4.0"

dev_dependencies:
  build_runner: ^1.10.0
  build_resolvers: ">=1.3.10"
